version: "3.9"

services:
  db:
    image: postgres:14
    container_name: my_twitter_test_db
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=test_microblog_db
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_twitter_test_web
    depends_on:
      - db
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://testuser:testpass@db:5432/test_microblog_db
    volumes:
      - ./uploads:/app/uploads
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  test_db_data:
